"""Store interface. The SQL implementation is the only one today; the
interface exists so Postgres (or anything else) can be added later without
touching the engine."""
from __future__ import annotations

from typing import Iterable, Protocol

from agency.domain.graph import Edge, Node
from agency.domain.runs import CostEntry, Event, InboxItem, Job, Project, Run


class Store(Protocol):
    # projects
    def put_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project | None: ...
    def list_projects(self) -> list[Project]: ...
    def delete_project(self, project_id: str) -> None: ...

    # nodes
    def put_node(self, node: Node) -> Node: ...
    def get_node(self, node_id: str, version: int | None = None) -> Node | None: ...
    def get_nodes(self, node_ids: Iterable[str]) -> list[Node]: ...
    def list_nodes(self, project_id: str | None = None, type: str | None = None,
                   scope: str | None = None, status: str | None = None,
                   limit: int | None = None) -> list[Node]: ...
    def node_versions(self, node_id: str) -> list[Node]: ...
    def search_nodes(self, text: str, project_id: str | None = None,
                     type: str | None = None, limit: int = 50) -> list[Node]: ...
    def delete_node(self, node_id: str) -> None: ...

    # edges
    def add_edge(self, edge: Edge) -> None: ...
    def edges_from(self, src: str, type: str | None = None) -> list[Edge]: ...
    def edges_to(self, dst: str, type: str | None = None) -> list[Edge]: ...
    def list_edges(self, project_id: str, type: str | None = None) -> list[Edge]: ...
    def remove_edge(self, src: str, dst: str, type: str) -> None: ...

    # ids
    def next_ids(self, prefix: str, project_id: str | None, n: int = 1) -> list[str]: ...
    def bump_counter(self, prefix: str, project_id: str | None, at_least: int) -> None: ...

    # runs / jobs
    def put_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, project_id: str | None = None, status: str | None = None) -> list[Run]: ...
    def put_job(self, job: Job) -> None: ...
    def get_job(self, job_id: str) -> Job | None: ...
    def list_jobs(self, run_id: str) -> list[Job]: ...

    # inbox
    def put_inbox(self, item: InboxItem) -> None: ...
    def get_inbox(self, item_id: str) -> InboxItem | None: ...
    def list_inbox(self, project_id: str | None = None, status: str | None = None,
                   run_id: str | None = None) -> list[InboxItem]: ...

    # events / costs
    def append_event(self, event: Event) -> Event: ...
    def list_events(self, since_seq: int = 0, project_id: str | None = None,
                    run_id: str | None = None, limit: int = 500) -> list[Event]: ...
    def add_cost(self, entry: CostEntry) -> None: ...
    def list_costs(self, project_id: str | None = None, run_id: str | None = None) -> list[CostEntry]: ...
    def sum_cost(self, project_id: str | None = None, run_id: str | None = None) -> float: ...

    def close(self) -> None: ...
