#!/usr/bin/env python3
"""Generate native Claude Code subagent stubs from agents/workers/ definitions.

The canonical worker definitions live in agents/workers/**/*.md (that is what
you edit, and what the Mission Control UI renders). This script generates a
thin stub per worker in .claude/agents/<name>.md so Claude Code can spawn it
natively with the right model and tool restrictions enforced by the harness.

Run after adding, renaming, or removing a worker:
  python3 scripts/gen_agent_stubs.py           # write/refresh stubs
  python3 scripts/gen_agent_stubs.py --check   # exit 1 if stubs are stale

Never edit generated stubs by hand — change the worker file or the
ASSIGNMENTS table below, then regenerate.
"""

import argparse
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKERS_DIR = os.path.join(REPO_ROOT, "agents", "workers")
AGENTS_DIR = os.path.join(REPO_ROOT, ".claude", "agents")

GENERATED_MARK = "GENERATED by scripts/gen_agent_stubs.py"

FILE_TOOLS = "Read, Write, Edit, Grep, Glob"

# (model, tools) per agent. model=None or tools=None → omit that key.
# tools=None means the agent inherits all tools (needed for MCP search tools,
# whose names are install-specific and fragile to enumerate).
ASSIGNMENTS = {
    # ideation
    "idea_evaluator": ("opus", FILE_TOOLS),
    # retrievers
    "literature_searcher": ("haiku", None),
    "web_scraper": ("haiku", None),
    "patent_scanner": ("haiku", None),
    "call_parser": ("sonnet", FILE_TOOLS + ", Bash"),
    "eligibility_parser": ("haiku", FILE_TOOLS + ", Bash"),
    "feedback_parser": ("sonnet", FILE_TOOLS + ", Bash"),
    # synthesizers
    "state_of_art_synthesizer": ("opus", FILE_TOOLS),
    "novelty_mapper": ("opus", FILE_TOOLS),
    "gap_analyzer": ("opus", FILE_TOOLS),
    # writers
    "excellence_writer": ("sonnet", FILE_TOOLS),
    "impact_writer": ("sonnet", FILE_TOOLS),
    "implementation_writer": ("sonnet", FILE_TOOLS),
    "abstract_writer": ("sonnet", FILE_TOOLS),
    "feedback_applier": ("sonnet", FILE_TOOLS),
    # reviewers
    "scientific_reviewer": ("opus", "Read, Write, Grep, Glob"),
    "adversarial_evaluator_simulator": ("opus", "Read, Write, Grep, Glob"),
    "compliance_checker": ("haiku", "Read, Write, Grep, Glob, Bash"),
    # finance
    "financial_modeler": ("sonnet", FILE_TOOLS + ", Bash"),
    "financial_narrative_writer": ("sonnet", FILE_TOOLS + ", Bash"),
    "financial_reviewer": ("opus", "Read, Write, Grep, Glob, Bash"),
    # business plan
    "bp_synthesizer": ("opus", FILE_TOOLS),
    "bp_commercial_writer": ("sonnet", FILE_TOOLS),
    "bp_financial_writer": ("sonnet", FILE_TOOLS),
    "bp_counterparty_writer": ("sonnet", FILE_TOOLS),
    "bp_risk_writer": ("sonnet", FILE_TOOLS + ", Bash"),
    "bp_reviewer": ("opus", "Read, Write, Grep, Glob"),
    # graphics — model chosen per figure by the orchestrator, so omitted
    "plot_renderer": (None, "Read, Write, Bash, Grep, Glob"),
    "concept_image_generator": (None, "Read, Write, Bash, Grep, Glob, WebFetch"),
}

# Not spawnable agents — no stub generated. These are interview protocols
# the orchestrator executes in the main conversation.
EXCLUDED = {"bp_interviewer", "idea_interviewer"}


def find_workers():
    """Map worker name -> repo-relative definition path."""
    workers = {}
    for root, _dirs, files in os.walk(WORKERS_DIR):
        for fname in sorted(files):
            if not fname.endswith(".md"):
                continue
            name = fname[:-3]
            workers[name] = os.path.relpath(os.path.join(root, fname), REPO_ROOT)
    return workers


def mission_first_sentence(path):
    """First sentence under ## Mission — same heuristic as the UI registry."""
    with open(os.path.join(REPO_ROOT, path)) as f:
        body = f.read()
    m = re.search(r"##\s+Mission\s*\n+([^\n]+)", body, re.I)
    text = m.group(1).strip() if m else ""
    sentence = re.split(r"(?<=[.!?])\s", text)[0] if text else ""
    return sentence or f"Worker agent defined in {path}"


def render_stub(name, rel_path):
    if name not in ASSIGNMENTS:
        print(f"warning: {name} has no ASSIGNMENTS entry — add one "
              f"(skipping)", file=sys.stderr)
        return None
    model, tools = ASSIGNMENTS[name]
    lines = ["---", f"name: {name}",
             f"description: {mission_first_sentence(rel_path)}"]
    if model:
        lines.append(f"model: {model}")
    if tools:
        lines.append(f"tools: {tools}")
    lines += [
        "---",
        f"<!-- {GENERATED_MARK} — edit {rel_path} instead -->",
        f"You are the {name} agent. Read `{rel_path}` and follow it exactly as "
        "your role definition. Your task-specific inputs (project, dedupe_key, "
        "input/output paths, wiki context) are in the task prompt below.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify stubs are current; exit 1 if stale")
    args = parser.parse_args()

    workers = find_workers()
    expected = {}
    for name, rel_path in sorted(workers.items()):
        if name in EXCLUDED:
            continue
        stub = render_stub(name, rel_path)
        if stub is not None:
            expected[name] = stub

    os.makedirs(AGENTS_DIR, exist_ok=True)
    stale, orphans = [], []

    existing = {f[:-3] for f in os.listdir(AGENTS_DIR)
                if f.endswith(".md")}
    for name in existing - set(expected):
        path = os.path.join(AGENTS_DIR, f"{name}.md")
        with open(path) as f:
            if GENERATED_MARK in f.read():
                orphans.append(name)

    for name, content in expected.items():
        path = os.path.join(AGENTS_DIR, f"{name}.md")
        current = None
        if os.path.exists(path):
            with open(path) as f:
                current = f.read()
        if current != content:
            stale.append(name)
            if not args.check:
                with open(path, "w") as f:
                    f.write(content)

    if not args.check:
        for name in orphans:
            os.remove(os.path.join(AGENTS_DIR, f"{name}.md"))

    if args.check:
        if stale or orphans:
            print(f"stale stubs: {stale}, orphaned stubs: {orphans}",
                  file=sys.stderr)
            sys.exit(1)
        print(f"{len(expected)} stubs up to date")
    else:
        print(f"wrote {len(stale)} stub(s), removed {len(orphans)} orphan(s), "
              f"{len(expected)} total in .claude/agents/")


if __name__ == "__main__":
    main()
